package net.sprocketgames.worldawakened.rules.runtime;

public enum WorldAwakenedRejectionReason {
    FEATURE_DISABLED,
    CONFIG_GATE_FAILED,
    INTEGRATION_INACTIVE,
    SELECTOR_MISMATCH,
    STAGE_CONDITION_FAILED,
    WORLD_CONTEXT_CONDITION_UNAVAILABLE,
    RECURSION_BLOCKED,
    COOLDOWN_ACTIVE,
    ONE_SHOT_CONSUMED,
    CHANCE_ROLL_FAILED,
    EXCLUSIVE_CONFLICT,
    HARD_CAP_REACHED,
    INVALID_REFERENCED_OBJECT,
    SAFE_ZONE_BLOCKED
}

