package net.sprocketgames.worldawakened.debug;

public final class WorldAwakenedDiagnosticCodes {
    public static final String STAGE_REF_MISSING = "WA_STAGE_REF_MISSING";
    public static final String SCHEMA_UNSUPPORTED = "WA_SCHEMA_UNSUPPORTED";
    public static final String ASCENSION_REWARD_INVALID = "WA_ASCENSION_REWARD_INVALID";
    public static final String RULE_RECURSION_BLOCKED = "WA_RULE_RECURSION_BLOCKED";
    public static final String PRESSURE_TIER_PROVIDER_INVALID = "WA_PRESSURE_TIER_PROVIDER_INVALID";
    public static final String CODEC_PARSE_FAILED = "WA_CODEC_PARSE_FAILED";
    public static final String DUPLICATE_ID = "WA_DUPLICATE_ID";
    public static final String MISSING_REQUIRED_FIELD = "WA_MISSING_REQUIRED_FIELD";
    public static final String INVALID_REFERENCE = "WA_INVALID_REFERENCE";
    public static final String INVALID_CONDITION_TYPE = "WA_INVALID_CONDITION_TYPE";
    public static final String INVALID_ACTION_TYPE = "WA_INVALID_ACTION_TYPE";
    public static final String CONFIG_GATE_INVALID = "WA_CONFIG_GATE_INVALID";
    public static final String INTEGRATION_INACTIVE = "WA_INTEGRATION_INACTIVE";
    public static final String SELECTOR_INVALID = "WA_SELECTOR_INVALID";
    public static final String POOL_SELECTION_IMPOSSIBLE = "WA_POOL_SELECTION_IMPOSSIBLE";
    public static final String INVASION_COMPOSITION_INVALID = "WA_INVASION_COMPOSITION_INVALID";
    public static final String COMPONENT_ARRAY_EMPTY = "WA_COMPONENT_ARRAY_EMPTY";
    public static final String COMPONENT_TYPE_UNKNOWN = "WA_COMPONENT_TYPE_UNKNOWN";
    public static final String COMPONENT_COMPOSITION_INVALID = "WA_COMPONENT_COMPOSITION_INVALID";
    public static final String COMPONENT_PARAMETERS_INVALID = "WA_COMPONENT_PARAMETERS_INVALID";
    public static final String COMPONENT_NO_RUNTIME_RESULT = "WA_COMPONENT_NO_RUNTIME_RESULT";
    public static final String COMPONENT_BUDGET_EXCEEDED = "WA_COMPONENT_BUDGET_EXCEEDED";
    public static final String COMPONENT_DUPLICATE_UNSUPPORTED = "WA_COMPONENT_DUPLICATE_UNSUPPORTED";
    public static final String RELOAD_EXCEPTION = "WA_RELOAD_EXCEPTION";
    public static final String ASCENSION_RECONCILE_COMPONENT_PARAM_INVALID = "WA_ASCENSION_RECONCILE_COMPONENT_PARAM_INVALID";
    public static final String ASCENSION_RECONCILE_ATTRIBUTE_MISSING = "WA_ASCENSION_RECONCILE_ATTRIBUTE_MISSING";
    public static final String ASCENSION_RECONCILE_UNSAFE_SHARED_EFFECT = "WA_ASCENSION_RECONCILE_UNSAFE_SHARED_EFFECT";
    public static final String PLAYER_FOREIGN_MODIFIER_PRESERVED = "WA_PLAYER_FOREIGN_MODIFIER_PRESERVED";
    public static final String PLAYER_ATTRIBUTE_SURFACE_MISSING = "WA_PLAYER_ATTRIBUTE_SURFACE_MISSING";
    public static final String PLAYER_EFFECT_SURFACE_MISSING = "WA_PLAYER_EFFECT_SURFACE_MISSING";
    public static final String REWARD_COMPONENT_SKIPPED_UNAVAILABLE_SURFACE = "WA_REWARD_COMPONENT_SKIPPED_UNAVAILABLE_SURFACE";
    public static final String REWARD_CARRIER_TYPE_MISSING = "WA_REWARD_CARRIER_TYPE_MISSING";
    public static final String REWARD_CARRIER_REFRESH_FAILED = "WA_REWARD_CARRIER_REFRESH_FAILED";
    public static final String GAMEPLAY_CARRIER_UNAVAILABLE = "WA_GAMEPLAY_CARRIER_UNAVAILABLE";
    public static final String VISUAL_CARRIER_UNAVAILABLE = "WA_VISUAL_CARRIER_UNAVAILABLE";
    public static final String ASC_SUPPRESSION_APPLIED = "WA_ASC_SUPPRESSION_APPLIED";
    public static final String ASC_SUPPRESSION_REMOVED = "WA_ASC_SUPPRESSION_REMOVED";
    public static final String ASC_SUPPRESSION_INVALID_PARTIAL = "WA_ASC_SUPPRESSION_INVALID_PARTIAL";
    public static final String ASC_SUPPRESSION_GROUP_REQUIRED = "WA_ASC_SUPPRESSION_GROUP_REQUIRED";
    public static final String ASC_COMPONENT_NOT_SUPPRESSIBLE = "WA_ASC_COMPONENT_NOT_SUPPRESSIBLE";
    public static final String ASC_SUPPRESSION_TARGET_UNKNOWN = "WA_ASC_SUPPRESSION_TARGET_UNKNOWN";
    public static final String ASC_SUPPRESSED_DEFINITION_MISSING = "WA_ASC_SUPPRESSED_DEFINITION_MISSING";
    public static final String ENTITY_RUNTIME_SURFACE_MISSING = "WA_ENTITY_RUNTIME_SURFACE_MISSING";
    public static final String MUTATOR_COMPONENT_SKIPPED_UNAVAILABLE_SURFACE = "WA_MUTATOR_COMPONENT_SKIPPED_UNAVAILABLE_SURFACE";
    public static final String RUNTIME_INSTANCE_MISSING_DEFINITION = "WA_RUNTIME_INSTANCE_MISSING_DEFINITION";
    public static final String COMPILED_GRAPH_MIXED_STATE_BLOCKED = "WA_COMPILED_GRAPH_MIXED_STATE_BLOCKED";
    public static final String FOREIGN_STATE_PRESERVATION_REQUIRED = "WA_FOREIGN_STATE_PRESERVATION_REQUIRED";
    public static final String RECONCILE_OWNERSHIP_VIOLATION = "WA_RECONCILE_OWNERSHIP_VIOLATION";

    private WorldAwakenedDiagnosticCodes() {
    }
}

